version: '3'

services:
  node_backend:
    container_name: node_teste
    image: node_teste:0.0.4
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=test_db
      - PGUSER=admin
      - PGPASSWORD=admin
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports:
      - "5430:5430"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}